### PR TITLE
Setup ssl-protocol=any by default and add ssl-errors option

### PR DESCRIPTION
**Pull request by zloylos**
Add ignore ssl errors and set ssl-protocol=any by default

### CODE REVIEW

**Comment by nathanboktae** [comment]
Since 1.9.8 the default SSL protocol is now `tlsv1` not `sslv3`. This is more secure than `any`. See ariya/phantomjs#12655.

I like the other fix if you back out `any`.

**Comment by zloylos** [comment]
ok, I've updated PR.
Look, please.

**Comment by nathanboktae** [comment]
Did you forget to push? Still only 1 commit.

**Comment by zloylos** [comment]
No, I've updated current commit :)

**Comment by nathanboktae** [comment]
FYI if you ever need to provide additional phantom args, `phantomjs lib/mocha-phantomjs.coffee <page> <reporter> <config>` is something we support (semver wise)

**Comment by zloylos** [comment]
Up. Now ignore-ssl-errors is boolean.

**Comment by nathanboktae** [comment]
`mocha-phantomjs` 4.0.0 now passes all unknown options along to phantomjs.

**Pull request closed without merging**
